version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-server
    environment:
      POSTGRES_DB: construction
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge

